apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ .Release.Name }}-my-dags-configmap
data:
    {{- $dags := .Files.Glob "dags/*" }}
    {{- range $name, $content := $dags }}
    {{ base $name }}: |-
{{  $content | toString | indent 8 }}
    {{- end }}