apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-copy-dags
  annotations:
    "helm.sh/hook": "post-install, post-upgrade"
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": "hook-succeeded" # Job deletes on success
spec:
  template:
    spec:
      containers:
      - name: copy-dags
        image: {{ .Values.acr.name }}.azurecr.io/{{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy}}
        command: ["/bin/sh", "-c"]
        args:
          - |
            PROJECT_NAME=$(cat /config.yaml | grep project_name | awk '{print $2}')
            echo "Project name: $PROJECT_NAME"
            DEST_DIR="/opt/airflow/dags/$PROJECT_NAME"
            if [ ! -d "$DEST_DIR" ]; then
                mkdir -p "$DEST_DIR"
            fi

            echo "Listing files in /dags before copying:"
            ls -al /dags
            echo "Removing previous versions..."
            rm -rf "$DEST_DIR/*"
            echo "Copying files from /dags to /mnt/dags..."
            cp -RL /dags/* "$DEST_DIR/"
            echo "Listing files in /opt/airflow/dags/$PROJECT_NAME after copying:"
            ls -al "$DEST_DIR"
        volumeMounts:
        - name: dags
          mountPath: /opt/airflow/dags
      restartPolicy: Never
      volumes:
      - name: dags
        persistentVolumeClaim:
          claimName: {{ .Values.airflow.pvc }}
      imagePullSecrets:
      - name: {{ .Values.acr.secretName }}
        

