apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: {{ .Release.Name }}-com-vol
spec:
    storageClassName: standard
    accessModes:
        - ReadWriteMany
    resources:
        requests:
            storage: 4Gi