apiVersion: v1
kind: Pod
metadata:
  name: pvc-inspector
spec:
  containers:
  - name: pvc-inspector
    image: busybox
    command: ["/bin/sh", "-c", "sleep 3600"]
    volumeMounts:
    - name: pvc
      mountPath: /mnt
  volumes:
  - name: pvc
    persistentVolumeClaim:
      claimName: wiki-dags-com-vol  # Replace with your PVC name
