apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: wiki-dags-com-vol
spec:
    storageClassName: standard
    accessModes:
        - ReadWriteMany
    resources:
        requests:
            storage: 4Gi